import type { Advisor, Property, User } from "@/lib/types";

export const initialAdvisors: Advisor[] = [
  {
    id: "adv-1",
    name: "Ayşe Demir",
    title: "Kıdemli Konut Danışmanı",
    phone: "+90 532 111 22 33",
    whatsapp: "+905321112233",
    email: "ayse.demir@demolanding.com",
    focusArea: "Kadıköy / Moda",
  },
  {
    id: "adv-2",
    name: "Mehmet Kaya",
    title: "Yatırım Uzmanı",
    phone: "+90 533 444 55 66",
    whatsapp: "+905334445566",
    email: "mehmet.kaya@demolanding.com",
    focusArea: "Beşiktaş / Levent",
  },
  {
    id: "adv-3",
    name: "Selin Yıldız",
    title: "Lüks Portföy Danışmanı",
    phone: "+90 534 777 88 99",
    whatsapp: "+905347778899",
    email: "selin.yildiz@demolanding.com",
    focusArea: "Sarıyer / Zekeriyaköy",
  },
];

export const initialUsers: User[] = [
  {
    id: "usr-1",
    name: "Portal Admin",
    role: "admin",
    email: "admin@demolanding.com",
    phone: "+90 212 900 00 01",
    username: "admin",
    password: "admin123",
  },
  {
    id: "usr-2",
    name: "Ayşe Demir",
    role: "advisor",
    email: "ayse.demir@demolanding.com",
    phone: "+90 532 111 22 33",
    username: "ayse",
    password: "ayse123",
    advisorId: "adv-1",
  },
  {
    id: "usr-3",
    name: "İçerik Editörü",
    role: "editor",
    email: "icerik@demolanding.com",
    phone: "+90 212 900 00 03",
    username: "icerik",
    password: "icerik123",
  },
];

export const initialProperties: Property[] = [
  {
    id: "prp-1",
    slug: "modada-deniz-manzarali-4-1-daire",
    title: "Moda'da Deniz Manzaralı 4+1 Daire",
    city: "İstanbul",
    district: "Kadıköy",
    neighborhood: "Caferağa",
    type: "Daire",
    price: 23500000,
    rooms: "4+1",
    areaM2: 210,
    floor: "6 / 8",
    heating: "Kombi",
    listingRef: "PN-0001",
    description:
      "Bağdat Caddesi'ne yürüme mesafesinde, önü kapanmaz manzaralı, geniş ailelere uygun, otoparklı premium daire.",
    highlights: [
      "Deniz manzarası",
      "Kapalı otopark",
      "Asansör",
      "Yatırıma uygun lokasyon",
    ],
    features: [
      "Akıllı ev altyapısı",
      "Ebeveyn banyosu",
      "Geniş balkon",
      "Yerden ısıtma",
      "7/24 güvenlik",
    ],
    advisorId: "adv-1",
    coverColor: "linear-gradient(120deg, #0f766e, #2dd4bf)",
    imageLabels: ["Salon", "Mutfak", "Ebeveyn Odası"],
    publishedAt: "2026-03-12T10:30:00.000Z",
  },
  {
    id: "prp-2",
    slug: "leventte-kira-getirili-ofis-kati",
    title: "Levent'te Kira Getirili Ofis Katı",
    city: "İstanbul",
    district: "Beşiktaş",
    neighborhood: "Levent",
    type: "Ofis",
    price: 18900000,
    rooms: "Açık Plan",
    areaM2: 175,
    floor: "5 / 12",
    heating: "Merkezi",
    listingRef: "PN-0002",
    description:
      "Kurumsal kiracılı, yüksek kira çarpanına sahip, metroya çok yakın A sınıfı ofis yatırımı.",
    highlights: [
      "Hazır kiracılı",
      "Yüksek kira geliri",
      "Merkezi konum",
      "A sınıfı bina",
    ],
    features: [
      "Kartlı geçiş",
      "Açık otopark",
      "Merkezi iklimlendirme",
      "Toplantı odası",
    ],
    advisorId: "adv-2",
    coverColor: "linear-gradient(120deg, #1d4ed8, #60a5fa)",
    imageLabels: ["Cephe", "Çalışma Alanı", "Lobi"],
    publishedAt: "2026-03-11T08:00:00.000Z",
  },
  {
    id: "prp-3",
    slug: "zekeriyakoyde-bahceli-luks-villa",
    title: "Zekeriyaköy'de Bahçeli Lüks Villa",
    city: "İstanbul",
    district: "Sarıyer",
    neighborhood: "Zekeriyaköy",
    type: "Villa",
    price: 42500000,
    rooms: "6+2",
    areaM2: 480,
    floor: "Müstakil",
    heating: "Yerden Isıtma",
    listingRef: "PN-0003",
    description:
      "Özel havuzlu, bağımsız bahçeli, güvenlikli sitede konumlanan anahtar teslim aile villası.",
    highlights: [
      "Özel havuz",
      "Müstakil bahçe",
      "Kapalı garaj",
      "Site güvenliği",
    ],
    features: [
      "Akıllı ev sistemi",
      "Şömine",
      "Yardımcı odası",
      "Sinema odası",
      "Fitness alanı",
    ],
    advisorId: "adv-3",
    coverColor: "linear-gradient(120deg, #7c2d12, #fb923c)",
    imageLabels: ["Bahçe", "Salon", "Havuz"],
    publishedAt: "2026-03-10T14:15:00.000Z",
  },
  {
    id: "prp-4",
    slug: "nisantasinda-yuksek-kat-rezidans",
    title: "Nişantaşı'nda Yüksek Kat Rezidans",
    city: "İstanbul",
    district: "Şişli",
    neighborhood: "Harbiye",
    type: "Rezidans",
    price: 31800000,
    rooms: "3+1",
    areaM2: 190,
    floor: "22 / 30",
    heating: "Merkezi",
    listingRef: "PN-0004",
    description:
      "Concierge, vale ve sosyal tesis imkanlarıyla şehir merkezinde prestijli yaşam fırsatı.",
    highlights: ["Panoramik şehir manzarası", "Vale", "Concierge", "Sosyal tesis"],
    features: [
      "Kapalı havuz",
      "Spa",
      "Çocuk oyun alanı",
      "Kuru temizleme hizmeti",
    ],
    advisorId: "adv-2",
    coverColor: "linear-gradient(120deg, #7e22ce, #c084fc)",
    imageLabels: ["Salon", "Mutfak", "Teras"],
    publishedAt: "2026-03-09T11:45:00.000Z",
  },
  {
    id: "prp-5",
    slug: "izmir-urla-yatirimlik-imarli-arsa",
    title: "İzmir Urla'da Yatırımlık İmarlı Arsa",
    city: "İzmir",
    district: "Urla",
    neighborhood: "Gülbahçe",
    type: "Arsa",
    price: 9700000,
    rooms: "-",
    areaM2: 920,
    floor: "-",
    heating: "-",
    listingRef: "PN-0005",
    description:
      "Ana yola cepheli, villa imarlı, uzun vadeli değer artışı potansiyeline sahip yatırım arsası.",
    highlights: [
      "Villa imarı",
      "Ana yola cephe",
      "Tapu hazır",
      "Hızlı satış imkanı",
    ],
    features: [
      "Elektrik altyapısı",
      "Su bağlantısı",
      "Kadastral yol",
      "Bölge gelişim planı",
    ],
    advisorId: "adv-1",
    coverColor: "linear-gradient(120deg, #166534, #4ade80)",
    imageLabels: ["Arazi Görünümü", "Yol Cephesi", "Bölge Planı"],
    publishedAt: "2026-03-08T09:20:00.000Z",
  },
];
